<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HopocalypseNow.FrontendApi.Domain\HopocalypseNow.FrontendApi.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Core" Version="1.43.0" />
      <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.1" />
      <PackageReference Include="HotChocolate" Version="13.9.12" />
      <PackageReference Include="HotChocolate.Types" Version="13.9.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="8.0.8" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Azure.Messaging.ServiceBus">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\azure.messaging.servicebus\7.17.5\lib\netstandard2.0\Azure.Messaging.ServiceBus.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
