@startuml "Container Diagram"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Compute/AzureAppService.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Integration/AzureServiceBus.puml
!includeurl AzurePuml/Integration/AzureServiceBusTopic.puml
!includeurl AzurePuml/Storage/AzureStorage.puml

' Person(customer, "Customer")

System_Boundary(landingZone, "Landing Zone") {
    AzureAppService(api, "Frontend API", "GraphQL", "")
    AzureCosmosDb(cosmosDb, "Database", "CosmosDb", "")

    AzureApplicationInsights(appi, "Application Insights", "To be used for analytics and insights.")
    AzureStorage(st, "Storage Account", "Azure Table Storage", "Storage account to be used by function apps.")
    AzureCosmosDb(orderDb, "Order Database", "CosmosDb Database")

    ' LAYOUT
    Lay_R(st, appi)

    ' RELATIONS
    Rel_D(api, cosmosDb, "")
    Rel_R(api, st, "")
    Rel_D(st, orderDb, "Order information")
}

System_Boundary(orders, "Orders") {
    AzureFunction(orderProcessor, "Order Processor", $processorTech, ".NET Serverless Function")

    ' RELATIONS
    Rel_D(orderDb, orderProcessor, "")
}

@enduml
