@startuml

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureC4Integration.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Databases/AzureSqlDatabase.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Compute/AzureAppService.puml
!includeurl AzurePuml/Integration/AzureServiceBus.puml
!includeurl AzurePuml/Integration/AzureServiceBusTopic.puml
!includeurl AzurePuml/Storage/AzureStorage.puml
!includeurl AzurePuml/AIMachineLearning/AzureMachineLearningService.puml

title Hopocalypse Now - Best Beershop Online - Context

' TEXTS
!$functionTech = "Azure Serverless Function (.NET)"

Person(user, "User")

AzureWebApp(webApp, "Web App", "Azure WebApp, Blazor, C#", "The web shop where customers can order beers.")
AzureWebApp(api, "GraphQL API", "Azure Serverless Function, GraphQl, Hot Chocolate, C#", "")
AzureCosmosDb(cosmosDb, "Document DB", "SQL API, 400 RUs")
AzureServiceBus(azureServiceBus, "Azure Service Bus", "Azure Service Bus", "")

AzureFunction(orderFunction, "Order Processor", $functionTech)


' RELATIONS
Rel(user, webApp, "Uses", "HTTPS")
Rel(webApp, api, "Uses", "HTTPS")
Rel(api, cosmosDb, "Read from and writes to", "SQL API")
Rel(api, azureServiceBus, "Puts events in", "Azure Service Bus Topic")
Rel(azureServiceBus, orderFunction, "Process orders")
Rel_R(orderFunction, cosmosDb, "Storing order information")

@enduml