name: Azure Infrastructure Deployment for the Landingzone
on: 
  workflow_dispatch:
  push:
    paths:
      - landingzone/infra/**
      
env:
  PROJECT_NAME: "hn"
  LOCATION: "westeurope"
  BICEP_TEMPLATE: "landingzone/infra/main.bicep"

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
          
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:

#     - name: Checkout code
#       uses: actions/checkout@main

#     - name: Log into Azure
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     - name: deployment-what-if
#       uses: Azure/deployment-what-if-action@v1.0.0
#       with:
#         subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroup: ${{ secrets.AZURE_RG }}
#         templateFile: ${{ env.BICEP_TEMPLATE }}
#         additionalParameters: 'projectName=${{ env.PROJECT_NAME }} location=${{ env.LOCATION }}'
        
#     - name: Deploy Bicep file
#       uses: azure/arm-deploy@v1
#       with:
#         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
#         resourceGroupName: ${{ secrets.AZURE_RG }}
#         template: ${{ env.BICEP_TEMPLATE }}
#         parameters: 'projectName=${{ env.PROJECT_NAME }} location=${{ env.LOCATION }}'
#         failOnStdErr: false
