name: Landingzone - Azure Infrastructure Deployment
on: 
  workflow_dispatch:
  push:
    paths:
      - landingzone/infra/**
      
env:
  PROJECT_NAME: "hn"
  LOCATION: "westeurope"
  DB_LOCATION: "northeurope"
  BICEP_TEMPLATE: "landingzone/infra/main.bicep"

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Checkout code
      uses: actions/checkout@main
    
    - name: 'What-If Bicep Deployment'
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          az deployment sub what-if \
            --template-file ${{ env.BICEP_TEMPLATE }} \
            --location ${{ env.LOCATION }} \
            --parameters projectName=${{ env.PROJECT_NAME }} location=${{ env.LOCATION }} dbLocation=${{ env.DB_LOCATION}}

    - name: 'Bicep Deployment'
      uses: Azure/cli@v2.0.0
      with:
        inlineScript: |
          az deployment sub create \
            --template-file ${{ env.BICEP_TEMPLATE }} \
            --location ${{ env.LOCATION }} \
            --parameters projectName=${{ env.PROJECT_NAME }} location=${{ env.LOCATION }} dbLocation=${{ env.DB_LOCATION}}

          
        # Azure CLI version to be used to execute the script. If not provided, latest version is used
        # azcliversion: # optional, default is agentazcliversion
          
    # - name: deployment-what-if
    #   uses: Azure/deployment-what-if-action@v1.0.0
    #   with:
    #     subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroup: ${{ secrets.AZURE_RG }}
    #     templateFile: ${{ env.BICEP_TEMPLATE }}
    #     additionalParameters: 'projectName=${{ env.PROJECT_NAME }} location=${{ env.LOCATION }}'
        
    # - name: Deploy Bicep file
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ secrets.AZURE_RG }}
    #     template: ${{ env.BICEP_TEMPLATE }}
    #     parameters: 'projectName=${{ env.PROJECT_NAME }} location=${{ env.LOCATION }}'
    #     failOnStdErr: false

