name: Spoke - Frontend - Deploy Frontend WebApp

on: 
  workflow_dispatch:
  push:
    paths:
      - spokes/frontend/**

env:
  AZURE_WEBAPP_NAME: 'app-hn-frontend-zjllqjptqbkey'
  AZURE_WEBAPP_PACKAGE_PATH: './spokes/frontend/src/HopocalypseNow.Frontend.BlazorApp'
  AZURE_WEBAPP_SOLUTION_FILE: './spokes/frontend/src/HopocalypseNow.Frontend.sln'
  DOTNET_VERSION: '6.0.x'                   

permissions:
  id-token: write
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4.1.4
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
       
    - name: Build with dotnet
      run: dotnet build ${{env.AZURE_WEBAPP_SOLUTION_FILE}} --configuration Release

    - name: dotnet publish
      run: dotnet publish ${{env.AZURE_WEBAPP_SOLUTION_FILE}} --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job#Reference a specific upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
